-- =============================================
-- Legal Case Management System Database Schema
-- Generated by Entity Framework Core
-- =============================================

-- Create Tables

-- Lawyers Table
CREATE TABLE [Lawyers] (
    [LawyerId] int NOT NULL IDENTITY,
    [FirstName] nvarchar(100) NOT NULL,
    [LastName] nvarchar(100) NOT NULL,
    [Email] nvarchar(200) NOT NULL,
    [Phone] nvarchar(20) NULL,
    [BarNumber] nvarchar(50) NULL,
    [Specialization] nvarchar(100) NULL,
    [IsActive] bit NOT NULL DEFAULT 1,
    [CreatedAt] datetime2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT [PK_Lawyers] PRIMARY KEY ([LawyerId])
);

-- Courts Table
CREATE TABLE [Courts] (
    [CourtId] int NOT NULL IDENTITY,
    [Name] nvarchar(200) NOT NULL,
    [Type] nvarchar(100) NULL,
    [Address] nvarchar(300) NULL,
    [City] nvarchar(100) NULL,
    [State] nvarchar(50) NULL,
    [ZipCode] nvarchar(20) NULL,
    [Phone] nvarchar(20) NULL,
    [IsActive] bit NOT NULL DEFAULT 1,
    [CreatedAt] datetime2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT [PK_Courts] PRIMARY KEY ([CourtId])
);

-- Parties Table
CREATE TABLE [Parties] (
    [PartyId] int NOT NULL IDENTITY,
    [FirstName] nvarchar(100) NOT NULL,
    [LastName] nvarchar(100) NOT NULL,
    [PartyType] nvarchar(50) NULL,
    [Email] nvarchar(200) NULL,
    [Phone] nvarchar(20) NULL,
    [Address] nvarchar(300) NULL,
    [City] nvarchar(100) NULL,
    [State] nvarchar(50) NULL,
    [ZipCode] nvarchar(20) NULL,
    [IsActive] bit NOT NULL DEFAULT 1,
    [CreatedAt] datetime2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT [PK_Parties] PRIMARY KEY ([PartyId])
);

-- Cases Table
CREATE TABLE [Cases] (
    [CaseId] int NOT NULL IDENTITY,
    [CaseNumber] nvarchar(50) NOT NULL,
    [Title] nvarchar(200) NOT NULL,
    [Description] nvarchar(1000) NULL,
    [AssignedLawyerId] int NOT NULL,
    [CourtId] int NOT NULL,
    [DateFiled] datetime2 NOT NULL,
    [Status] nvarchar(50) NOT NULL DEFAULT N'Active',
    [Outcome] nvarchar(500) NULL,
    [IsActive] bit NOT NULL DEFAULT 1,
    [CreatedAt] datetime2 NOT NULL DEFAULT GETUTCDATE(),
    [UpdatedAt] datetime2 NULL,
    CONSTRAINT [PK_Cases] PRIMARY KEY ([CaseId]),
    CONSTRAINT [FK_Cases_Lawyers_AssignedLawyerId] FOREIGN KEY ([AssignedLawyerId]) REFERENCES [Lawyers] ([LawyerId]) ON DELETE NO ACTION,
    CONSTRAINT [FK_Cases_Courts_CourtId] FOREIGN KEY ([CourtId]) REFERENCES [Courts] ([CourtId]) ON DELETE NO ACTION
);

-- CaseParties Junction Table
CREATE TABLE [CaseParties] (
    [CasePartyId] int NOT NULL IDENTITY,
    [CaseId] int NOT NULL,
    [PartyId] int NOT NULL,
    [Role] nvarchar(50) NOT NULL,
    [CreatedAt] datetime2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT [PK_CaseParties] PRIMARY KEY ([CasePartyId]),
    CONSTRAINT [FK_CaseParties_Cases_CaseId] FOREIGN KEY ([CaseId]) REFERENCES [Cases] ([CaseId]) ON DELETE CASCADE,
    CONSTRAINT [FK_CaseParties_Parties_PartyId] FOREIGN KEY ([PartyId]) REFERENCES [Parties] ([PartyId]) ON DELETE CASCADE
);

-- Hearings Table
CREATE TABLE [Hearings] (
    [HearingId] int NOT NULL IDENTITY,
    [CaseId] int NOT NULL,
    [CourtId] int NULL,
    [Date] datetime2 NOT NULL,
    [Time] time NOT NULL,
    [Location] nvarchar(200) NULL,
    [HearingType] nvarchar(100) NULL,
    [Remarks] nvarchar(500) NULL,
    [Status] nvarchar(50) NOT NULL DEFAULT N'Scheduled',
    [CreatedAt] datetime2 NOT NULL DEFAULT GETUTCDATE(),
    [UpdatedAt] datetime2 NULL,
    CONSTRAINT [PK_Hearings] PRIMARY KEY ([HearingId]),
    CONSTRAINT [FK_Hearings_Cases_CaseId] FOREIGN KEY ([CaseId]) REFERENCES [Cases] ([CaseId]) ON DELETE CASCADE,
    CONSTRAINT [FK_Hearings_Courts_CourtId] FOREIGN KEY ([CourtId]) REFERENCES [Courts] ([CourtId]) ON DELETE SET NULL
);

-- Deadlines Table
CREATE TABLE [Deadlines] (
    [DeadlineId] int NOT NULL IDENTITY,
    [CaseId] int NOT NULL,
    [DueDate] datetime2 NOT NULL,
    [Description] nvarchar(200) NOT NULL,
    [Priority] nvarchar(50) NOT NULL DEFAULT N'Medium',
    [IsCompleted] bit NOT NULL DEFAULT 0,
    [CompletedDate] datetime2 NULL,
    [Notes] nvarchar(500) NULL,
    [CreatedAt] datetime2 NOT NULL DEFAULT GETUTCDATE(),
    [UpdatedAt] datetime2 NULL,
    CONSTRAINT [PK_Deadlines] PRIMARY KEY ([DeadlineId]),
    CONSTRAINT [FK_Deadlines_Cases_CaseId] FOREIGN KEY ([CaseId]) REFERENCES [Cases] ([CaseId]) ON DELETE CASCADE
);

-- Create Indexes

-- Unique Indexes
CREATE UNIQUE INDEX [IX_Cases_CaseNumber] ON [Cases] ([CaseNumber]);
CREATE UNIQUE INDEX [IX_Lawyers_Email] ON [Lawyers] ([Email]);
CREATE UNIQUE INDEX [IX_Lawyers_BarNumber] ON [Lawyers] ([BarNumber]) WHERE [BarNumber] IS NOT NULL;

-- Composite Unique Index for CaseParties
CREATE UNIQUE INDEX [IX_CaseParties_CaseId_PartyId_Role] ON [CaseParties] ([CaseId], [PartyId], [Role]);

-- Performance Indexes
CREATE INDEX [IX_Cases_AssignedLawyerId] ON [Cases] ([AssignedLawyerId]);
CREATE INDEX [IX_Cases_CourtId] ON [Cases] ([CourtId]);
CREATE INDEX [IX_Cases_Status] ON [Cases] ([Status]);
CREATE INDEX [IX_Cases_IsActive] ON [Cases] ([IsActive]);
CREATE INDEX [IX_Cases_DateFiled] ON [Cases] ([DateFiled]);

CREATE INDEX [IX_CaseParties_CaseId] ON [CaseParties] ([CaseId]);
CREATE INDEX [IX_CaseParties_PartyId] ON [CaseParties] ([PartyId]);

CREATE INDEX [IX_Hearings_CaseId] ON [Hearings] ([CaseId]);
CREATE INDEX [IX_Hearings_CourtId] ON [Hearings] ([CourtId]);
CREATE INDEX [IX_Hearings_Date] ON [Hearings] ([Date]);
CREATE INDEX [IX_Hearings_Status] ON [Hearings] ([Status]);

CREATE INDEX [IX_Deadlines_CaseId] ON [Deadlines] ([CaseId]);
CREATE INDEX [IX_Deadlines_DueDate] ON [Deadlines] ([DueDate]);
CREATE INDEX [IX_Deadlines_IsCompleted] ON [Deadlines] ([IsCompleted]);
CREATE INDEX [IX_Deadlines_Priority] ON [Deadlines] ([Priority]);

-- Insert Sample Data

-- Sample Lawyers
INSERT INTO [Lawyers] ([FirstName], [LastName], [Email], [Phone], [BarNumber], [Specialization], [CreatedAt])
VALUES 
    ('John', 'Smith', 'john.smith@lawfirm.com', '555-0101', 'BAR001', 'Criminal Law', GETUTCDATE()),
    ('Sarah', 'Johnson', 'sarah.johnson@lawfirm.com', '555-0102', 'BAR002', 'Civil Law', GETUTCDATE());

-- Sample Courts
INSERT INTO [Courts] ([Name], [Type], [Address], [City], [State], [ZipCode], [Phone], [CreatedAt])
VALUES 
    ('Superior Court of Justice', 'Superior', '123 Justice Blvd', 'Downtown', 'CA', '90210', '555-0201', GETUTCDATE()),
    ('District Court', 'District', '456 Court Street', 'Midtown', 'CA', '90211', '555-0202', GETUTCDATE());

-- Sample Parties
INSERT INTO [Parties] ([FirstName], [LastName], [PartyType], [Email], [Phone], [Address], [City], [State], [ZipCode], [CreatedAt])
VALUES 
    ('Alice', 'Williams', 'Individual', 'alice.williams@email.com', '555-0301', '789 Main Street', 'Downtown', 'CA', '90210', GETUTCDATE()),
    ('Bob', 'Davis', 'Individual', 'bob.davis@email.com', '555-0302', '321 Oak Avenue', 'Uptown', 'CA', '90212', GETUTCDATE());

-- =============================================
-- Views for Common Queries
-- =============================================

-- View: Active Cases with Lawyer and Court Information
CREATE VIEW [vw_ActiveCases] AS
SELECT 
    c.[CaseId],
    c.[CaseNumber],
    c.[Title],
    c.[Description],
    c.[Status],
    c.[DateFiled],
    c.[CreatedAt],
    l.[FirstName] + ' ' + l.[LastName] AS [LawyerName],
    l.[Email] AS [LawyerEmail],
    l.[Specialization],
    ct.[Name] AS [CourtName],
    ct.[Type] AS [CourtType],
    ct.[City] AS [CourtCity]
FROM [Cases] c
INNER JOIN [Lawyers] l ON c.[AssignedLawyerId] = l.[LawyerId]
INNER JOIN [Courts] ct ON c.[CourtId] = ct.[CourtId]
WHERE c.[IsActive] = 1 AND l.[IsActive] = 1 AND ct.[IsActive] = 1;

-- View: Upcoming Hearings
CREATE VIEW [vw_UpcomingHearings] AS
SELECT 
    h.[HearingId],
    h.[Date],
    h.[Time],
    h.[Location],
    h.[HearingType],
    h.[Status],
    c.[CaseNumber],
    c.[Title] AS [CaseTitle],
    l.[FirstName] + ' ' + l.[LastName] AS [LawyerName],
    ct.[Name] AS [CourtName]
FROM [Hearings] h
INNER JOIN [Cases] c ON h.[CaseId] = c.[CaseId]
INNER JOIN [Lawyers] l ON c.[AssignedLawyerId] = l.[LawyerId]
LEFT JOIN [Courts] ct ON h.[CourtId] = ct.[CourtId]
WHERE c.[IsActive] = 1 
  AND h.[Status] = 'Scheduled' 
  AND h.[Date] > GETUTCDATE();

-- View: Overdue Deadlines
CREATE VIEW [vw_OverdueDeadlines] AS
SELECT 
    d.[DeadlineId],
    d.[DueDate],
    d.[Description],
    d.[Priority],
    c.[CaseNumber],
    c.[Title] AS [CaseTitle],
    l.[FirstName] + ' ' + l.[LastName] AS [LawyerName],
    DATEDIFF(day, d.[DueDate], GETUTCDATE()) AS [DaysOverdue]
FROM [Deadlines] d
INNER JOIN [Cases] c ON d.[CaseId] = c.[CaseId]
INNER JOIN [Lawyers] l ON c.[AssignedLawyerId] = l.[LawyerId]
WHERE c.[IsActive] = 1 
  AND d.[IsCompleted] = 0 
  AND d.[DueDate] < GETUTCDATE();

-- =============================================
-- Stored Procedures for Common Operations
-- =============================================

-- Procedure: Get Case Summary with Statistics
CREATE PROCEDURE [sp_GetCaseSummary]
    @CaseId INT
AS
BEGIN
    SELECT 
        c.*,
        l.[FirstName] + ' ' + l.[LastName] AS [LawyerName],
        ct.[Name] AS [CourtName],
        (SELECT COUNT(*) FROM [Hearings] WHERE [CaseId] = @CaseId) AS [TotalHearings],
        (SELECT COUNT(*) FROM [Hearings] WHERE [CaseId] = @CaseId AND [Status] = 'Completed') AS [CompletedHearings],
        (SELECT COUNT(*) FROM [Deadlines] WHERE [CaseId] = @CaseId) AS [TotalDeadlines],
        (SELECT COUNT(*) FROM [Deadlines] WHERE [CaseId] = @CaseId AND [IsCompleted] = 1) AS [CompletedDeadlines],
        (SELECT COUNT(*) FROM [Deadlines] WHERE [CaseId] = @CaseId AND [IsCompleted] = 0 AND [DueDate] < GETUTCDATE()) AS [OverdueDeadlines]
    FROM [Cases] c
    INNER JOIN [Lawyers] l ON c.[AssignedLawyerId] = l.[LawyerId]
    INNER JOIN [Courts] ct ON c.[CourtId] = ct.[CourtId]
    WHERE c.[CaseId] = @CaseId AND c.[IsActive] = 1;
END;

-- Procedure: Get Lawyer Caseload
CREATE PROCEDURE [sp_GetLawyerCaseload]
    @LawyerId INT
AS
BEGIN
    SELECT 
        l.*,
        (SELECT COUNT(*) FROM [Cases] WHERE [AssignedLawyerId] = @LawyerId AND [IsActive] = 1) AS [TotalCases],
        (SELECT COUNT(*) FROM [Cases] WHERE [AssignedLawyerId] = @LawyerId AND [IsActive] = 1 AND [Status] = 'Active') AS [ActiveCases],
        (SELECT COUNT(*) FROM [Cases] WHERE [AssignedLawyerId] = @LawyerId AND [IsActive] = 1 AND [Status] = 'Closed') AS [ClosedCases],
        (SELECT COUNT(*) 
         FROM [Hearings] h 
         INNER JOIN [Cases] c ON h.[CaseId] = c.[CaseId] 
         WHERE c.[AssignedLawyerId] = @LawyerId 
           AND c.[IsActive] = 1 
           AND h.[Status] = 'Scheduled' 
           AND h.[Date] BETWEEN GETUTCDATE() AND DATEADD(day, 30, GETUTCDATE())) AS [UpcomingHearings],
        (SELECT COUNT(*) 
         FROM [Deadlines] d 
         INNER JOIN [Cases] c ON d.[CaseId] = c.[CaseId] 
         WHERE c.[AssignedLawyerId] = @LawyerId 
           AND c.[IsActive] = 1 
           AND d.[IsCompleted] = 0 
           AND d.[DueDate] < GETUTCDATE()) AS [OverdueDeadlines]
    FROM [Lawyers] l
    WHERE l.[LawyerId] = @LawyerId AND l.[IsActive] = 1;
END;